# Generated by Django 3.0.4 on 2020-03-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
