# Generated by Django 3.0.4 on 2020-03-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now_add=True)),
                ('S_Description', models.TextField()),
                ('L_Description', models.TextField()),
                ('Author', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Tags', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blogs.Blogtags')),
            ],
        ),
    ]
