# Generated by Django 3.0.4 on 2020-03-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newscatgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Author', models.CharField(max_length=20)),
                ('Tags', models.CharField(max_length=60)),
                ('Image', models.ImageField(upload_to='pics')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.Newscatgory')),
            ],
        ),
    ]
